### ISSUE TITLE
Support new Link rel="preload" header

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/http2push-gae#1]
The `Link rel="preload"` is the new standard header as described in http://w3c.github.io/preload/. It would be good to preemptively support this. The `X-Associated-Content` is an old SPDY header. 

https://www.chromestatus.com/features/5757468554559488

**Comment by igrigorik** [comment]
Yes, please! Support for X-Associated-Content will be deprecated.

**Comment by ebidel** [comment]
I knew you'd stalk this repo! 

Question, is there priority in the `Link` header, or that's completely deprecated? Also is the `as=` final?

**Comment by igrigorik** [comment]
Yes, there is. It's an optional field but you should specify it where possible to give the UA and any intermediaries the context about type and priority of the resource:
- https://w3c.github.io/preload/#widl-HTMLLinkElement-as
- https://w3c.github.io/preload/#developer-server-and-proxy-initiated-fetching

p.s. current `as` is as "final" as any living spec can be :-)

**Comment by ebidel** [comment]
An priority level is gone?

**Comment by igrigorik** [comment]
Guessing you're thinking ["pr"](http://w3c.github.io/resource-hints/#hint-probability-pr-attribute), which is defined in Resource Hints spec?

The `pr` attribute is defined for speculative resource fetches: prefetch, prerender, preconnect. Preload, on the other hand, is a declarative fetch (the user agent _must_ fetch it), so `pr` is a noop.

**Comment by ebidel** [comment]
Got it. Thanks for clarifying @igrigorik. Hard to keep all these specs sorted.

**Comment by ebidel** [comment]
Added support for the spec'd header. The `X-Associated-Content` is also supported for now.

https://github.com/GoogleChrome/http2push-gae/blob/master/http2push.py
