### ISSUE TITLE
Support crossorigin resources

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/http2push-gae#10]
`Link: <https://fonts.example.com/font.woff>; rel=preload; as=font; crossorigin`

**Comment by igrigorik** [comment]
Server push is restricted to same origin resources..

**Comment by ebidel** [comment]
The above is from your spec. Is that no longer part of it?

**Comment by igrigorik** [comment]
rel=preload when executed by the client can fetch cross-origin resources. But the server responding to a request can only push same-origin resources -- i.e. example.com can't push resources that belong to widget.com. Does that make sense?

**Comment by ebidel** [comment]
https://w3c.github.io/preload/#developer-server-and-proxy-initiated-fetching. Example 5, last line. Isn't that cross origin?

**Comment by igrigorik** [comment]
It is. But there is a difference between _server push_ and initiating a preload on the client. When the client sees that header it'll begin fetching the resource, but the origin serving that header _cannot_ initiate push for it because it belongs to a different origin.

**Comment by ebidel** [comment]
Then, I guess I'm confused on how Example 5 could even work. It's effectively a noop if the server can't push it down. IOW, what does initiating a preload give you if the server cannot push the resource? I'm under the assumption preload === push but I suspect you're saying it's not the same :)

**Comment by igrigorik** [comment]
Yes, exactly. Take push out of the equation for a second.. When the client sees the preload link tag/header it dispatches the request for said resource -- it's a declarative fetch that doesn't block onload.

IF the server supports push and detects the Link header, it _can_ initiate push, at which point the client operation is a no-op.

**Comment by ebidel** [comment]
Thanks for the explanation dude!
