### ISSUE TITLE
Include the `as=type` attribute???

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/http2push-gae#12]
As discussed on https://github.com/GoogleChrome/chromium-dashboard/pull/246#issuecomment-148131006.

AFAIK, this isn't implemented anywhere, but spec'd. Not sure if the browser handles it yet.

Valid types: https://fetch.spec.whatwg.org/#concept-request-type

cc @igrigorik may know

**Comment by igrigorik** [comment]
It will be once we land support for preload. @yoavweiss is working on it for Chrome.

**Comment by ebidel** [comment]
Dupe of https://github.com/GoogleChrome/http2-push-manifest/issues/1. This should be handled over in the manifest generator.
