### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by rchedrese-va** [GoogleChrome/http2push-gae#13]
The example site only seems to push resources on Chrome Canary and even then I'm not quite getting the same results shown in your screenshot. Should this not work on all browsers that support HTTP2?

**Comment by ebidel** [comment]
I believe so. Other browser tooling is harder know for sure. I haven't found anything that beats chrome://net-internals/#export

**Comment by igrigorik** [comment]
AFAIK, everything should work with Firefox. Edge does not support push (yet?). Need to test on Safari.
