### ISSUE TITLE
Push doesn't work on custom domains.

### ISSUE THREAD

**Issue by rchedrese-va** [GoogleChrome/http2push-gae#16]
@ebidel mentioned this issue and it looks to still be occurring. Can you guys update this issue when it's fixed?

**Comment by ebidel** [comment]
I'm watching it very closely internally. Can't give an ETA, but it should be very soon. FWIW, it was supposed to be fixed last week but the push got delayed.

**Comment by ebidel** [comment]
I'll of course update this bug when the fix goes out and I've verified it works.

**Comment by ebidel** [comment]
Fixe in prod! Example: 

push: https://www.chromestatus.com/features
no push: https://www.chromestatus.com/features?nopush

**Comment by rchedrese-va** [comment]
Thanks @ebidel, much appreciated.
