### ISSUE TITLE
Chrome Warning of http2push

### ISSUE THREAD

**Issue by HW-Siew** [GoogleChrome/http2push-gae#21]
I used the http2push.py on server. At client side, i see "<link rel=preload> must have a valid `as` value" warning in console. Any idea what is wrong there?

**Comment by ebidel** [comment]
Are you pushing an html file? This is a known bug in chrome where document
as a type is not understood.

**Comment by HW-Siew** [comment]
Yes, I am pushing polymer element.  Thanks for the information.
