### ISSUE TITLE
Do you recommend minifying polymer elements?

### ISSUE THREAD

**Issue by cayblood** [GoogleChrome/http2push-gae#3]
http2 push seems to obviate vulcanize, but one aspect of vulcanize was minification. In your experience, is it worth minifying polymer components with http2 push, or do you think it's overkill?

**Comment by igrigorik** [comment]
You should definitely minify your resources, regardless of protocol or delivery mechanism. Minification is a form of content-aware compression.. and shipping fewer bytes is always a win.

**Comment by cayblood** [comment]
Thanks for the clarification.
